image: alpine/latest
packages:
  - hugo
  - rsync
  - npm
sources:
  - https://github.com/expertanalytics/xal
environment:
  prod_repo: git@github.com:expertanalytics/expertanalytics.github.io.git
  ssh_command: ssh -o StrictHostKeyChecking=no
secrets:
  - db8a8c85-48b3-4545-95f5-08109ebb57b1
tasks:
  - setup: |
      rm -rf public
  - build: |
      cd xal
      cd scripts/build-search-index && npm install && -
      ./scripts/build-search-index/build-index.js > static/gen/index.json
      hugo --minify --destination=../public || exit 1
  - deploy: |
      if [ $GITHUB_REF = refs/heads/master ]; then
          cd public
          echo expertanalytics.no > CNAME
          git init
          git config user.name builds.sr.ht
          git config user.email post@expertanalytics.no
          git config core.sshCommand "$ssh_command"
          git add .
          git commit -m 'Deploy from sr.ht'
          git push $prod_repo master --force
      else
          rsync -e "$ssh_command" --delete -rv \
              public/ deploy@dev.xal.no:www/pr/${GITHUB_REF##*/}
      fi
